# Generated by Django 2.2.4 on 2019-08-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('act', models.CharField(max_length=100)),
                ('track', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
